### ISSUE TITLE
Add ability to download stand-alone feed_info.txt

### ISSUE THREAD

**Issue by mlundblad** [geops/gtfsman#1]
trafiklab.se provides the feed_info.txt as a separate download (it also included in their .zips) which you can download without it counting as a download of the limited monthly usage for an API key.
It would be nice with a feature to pre-fetch this and compare against the one of the last download (would probably work by checking a file content hash).
Also, their servers don't seem to support HEAD requests, so the data is always downloaded every time update is run.

**Comment by patrickbr** [comment]
Sounds useful to me, I will look into it. Btw, atm the manager has the ability to check the last modified header of the remote feed - however, this feature is hidden and poorly documented. We are working on an updated version which integrates all the features we are already using in production.

**Comment by lb1c** [comment]
@patrickbr is this still active?
